<?php

namespace CalculationBundle\Repository;

/**
 * InvoicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoicesRepository extends \Doctrine\ORM\EntityRepository
{
}
